language: node_js
node_js:
- 11.7
addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  npm: true
  directories:
  - "~/.cache"
script:
- echo Starting back- and frontend, then running tests...
- cd backend/
- npm install
- npm start &
- echo Backend started....................
- cd ..
- cd frontend/
- npm install
- npm start &
- echo Frontend started..................
- $(npm bin)/cypress run
- npx mochawesome-merge --reportDir cypress/results > mochawesome.json
- cd cypress/results/
- npx mochawesome-report-generator mochawesome.json
- rm mochawesome.json
- cd .. && cd .. && cd .. && pwd
- ./buildnewandpushtoheroku.sh



before_deploy: "pwd && cd opintojenaikatauluttaja"
deploy:
  provider: heroku
  api_key:
    secure: BrC+W6EYbzzh8SX6H7ihctZBPXyiMlSMUrir2xQ3CsL8E1aPM65a4jciFLtZjSOPUTOWq3LzuKp05NRVNXBVEgwH0thq3ipM8HUpTMV2RxnSKNHF/ffSpIRD9PKsexaNPIewsLXnCIYg6ms+XRovn/JrdIWjZpBVRzvc1Oel0I39nnRV4SH9rVkqRM419Emwwtc8mF/+oQW5dTzHyEhd/0P7e5EQQeTQTE1TeBHCx3sxeSePTz51XRlqjtll0jhXQJLVqHKDOLDrp/0hb86i2k2gYoOWicJx76Jq5zRRW64L4PXBztd4oUEDkJAS7nLmrNDDYlvQGG+BEu1Q+anOeWfCvjvJsSIq7Lo3hynZkTlOD7aj5vedla3q5gVKZldM/5gglxfupBFq7PXgDC5dcaaEtmxSsXnP5II4vVcdzfnjbHVyWqoXPPzbkvcOHT+uRGF+QYvLvg0EyMODM01w2IoeVv13bYfKLGCCtBhtyMSFw4be5k4OZvllfKIQ9KzmGCWbfC3QphJUzKwtnY9LGhG7WNPhrSX+eGUfqcfNoQFRcThMdYxCQVBdKExgwIBwxPe87epUQ1Xot08OCBgkSosdLO0BwY7QA3WY87HcHkb7ysLnP72Q1KthElHgeVDmaJV1iNj/FSDPcLzWJU35UQ7SGXVAJQG2DtSHBvOCvRQ=
  skip_cleanup: true
