language: node_js
node_js:
- 10
addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  npm: true
  directories:
  - "~/.cache"
script:
- echo Starting back- and frontend, then running tests...
- cd backend/
- npm install
- npm start &
- echo Backend started....................
- cd ..
- cd frontend/aikatauluttaja
- npm install
- npm start &
- echo Frontend started..................
- "$(npm bin)/cypress run --record --key=8d934730-49e2-46ac-946b-63e79d9e1797 && cd
  .. && cd .. && ./buildnewandpushtoheroku.sh"
- pwd
deploy:
  provider: heroku
  api_key:
    secure: TlxbYa4rgF1NEiDqLDbSENwK3jLVPheJH2MiTE1savwGfCG7YhpKgrOrkbyDz4j981pgv0Sm2t/5UFjngeQ6uzo6k2jO/Lu+L39sKnud4+i70RY3WJsWyj0uYJ5meUuFZQb+iaw7ERpHmgZn3/ikcFsfFvjKcmNLVw/244cdFD11/IypQXdmNFcwtV+Vhq4VHuQ00+0qxWgBGCaFs6c1KzcVnnw1TJvArLgq2y91LKaOsfLD010DVDabjdYllSM9ybzuscEWV1+bbsZtcYTbDkMofvo6uF/rUKTiMsprFbdEris+UXnnsbenyeQk1wi5/gV599dIQZWcp1yVq3BWHV7fTfvTmfar9tVuCcwzUmkWHKoajUykR1P3h7tOQVDO85FwpPJaB4ntuc5xRae8yx6SkRkSuWmnwmna+MKeoJlVOWq6bNEtIJkUjVQkopOPWcTGRiwxW1CTigq1Vz41VvIkdZnaRXwA2TSGUuSgShHHkvxWP+yC3E4yQ472DG5e4c/XG4S4xQbUsK43ztgYZAzKQx7zTc03YrZ4iHPhV/UgpIirhO23kUUJ8IpsPdMZseL5m05s91lV+IXpw2H3iMtp0t8H+lpWLBhK2wyPNtd7z9lYx9YewLuidm/4yNvZnDvLvK2yp+CdMFLQRG2l3Osnz/fJgEpn1PWpw3EgmI8=
  skip_cleanup: true
